version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:
  postgres:
    container_name: cn_postgres
    image: postgres:bm
    networks:
      - default
    build:
      context: ./config/postgres
      dockerfile: Dockerfile
      args:
        - container_timezone=${CONTAINER_TIMEZONE}
    ports:
      - "45432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data

